# Test suite name
description: "Minimal Test Suite"

# Prompts
prompts:
  - file://prompt.txt

# Model providers
providers:
  - id: openai:gpt-3.5-turbo-1106

# Evaluation options
evaluateOptions:
  repeat: 1
